package jin.model;

// Generated 2015-4-21 10:51:58 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.validation.constraints.Pattern;

import org.hibernate.validator.constraints.Email;

/**
 * Sysinfo generated by hbm2java
 */
@Entity(name="Sysinfo")
public class Sysinfo implements java.io.Serializable {

	private long id;
	@Email
	private String email;
	private String phone;
	private String fax;
	private String address;

	public Sysinfo() {
	}

	public Sysinfo(long id) {
		this.id = id;
	}

	public Sysinfo(long id, String email, String phone,String fax, String address) {
		this.id = id;
		this.email = email;
		this.phone = phone;
		this.fax = fax;
		this.address = address;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "email", length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name="fax")
	public String getFax() {
		return fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "address", length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
